### ISSUE TITLE
Infinite shrine indicators

### ISSUE THREAD

**Issue by borb43** [mwoiii/artifact-of-prestige#1]
When adding the shrine indicator to the teleporter from previous stages it adds a new indicator every single frame. eventually this breaks the game and other particles stop appearing entirely, the game fails ro render projectiles, the game fails to broadcast messages to the chat and it generates large amounts of lag along with a few more minor issue

**Comment by mwoiii** [comment]
Are you able to provide any more context (any errors in the log, other mods, how to reproduce)? It sounds like the onStageStartGlobal event is being invoked every single frame for some reason, but that seems unlikely. I can try to implement potential solutions but there is no guarantee they will work
