### ISSUE TITLE
Artifact not showing up

### ISSUE THREAD

**Issue by anartoast** [mwoiii/artifact-of-prestige#2]
For some reason, after installing Starstorm2, it stopped showing up.

**Comment by mwoiii** [comment]
I don't see any immediate issues..
<img src="https://github.com/user-attachments/assets/6be8c113-8616-4b9a-b54e-f668e333e9e3" width="400" />
Are you playing with any other mods?

**Comment by anartoast** [comment]
Yes, here's my code: 0190adce-ab6f-b8fd-f2e4-27601d652344 (r2modman)

**Comment by mwoiii** [comment]
Thanks 🙂 the fix should hopefully be uploaded shortly

**Comment by anartoast** [comment]
np np
